name: Build and deploy

on:
  push:
    branches: [ "master" ]

env:
  BUCKET_NAME: dlb-web          # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: npm install
      run: |
        npm ci
        CI=false npm run build
    - name: deploy
      run: |
        aws s3 sync ./public s3://${{env.BUCKET_NAME}} --delete
